'salt',
  'butter',
  'sugar',
  'pepper',
  'eggs',
  'olive oil',
  'onions',
  'water',
  'garlic',
  'milk',
  'flour',
  'all-purpose flour',
  'garlic cloves',
  'baking powder',
  'unsalted butter',
  'sweet butter',
  'vanilla extract',
  'ground black pepper',
  'large eggs',
  'lemon juice',
  'kosher salt',
  'brown sugar',
  'lemon',
  'carrots',
  'baking soda',
  'sodium bicarbonate',
  'oil',
  'tomatoes',
  'vegetable oil',
  'honey',
  'extra-virgin olive oil',
  'cinnamon',
  'black pepper',
  'powdered sugar',
  'icing sugar',
  'vanilla',
  'granulated sugar',
  'sea salt',
  'heavy cream',
  'ground cinnamon',
  'sour cream',
  'potatoes',
  'paprika',
  'purple onion',
  'red onion',
  'parsley',
  'garlic powder',
  'soy sauce',
  'soya sauce',
  'cream cheese',
  'green onions',
  'shallots',
  'corn starch',
  'mayonnaise',
  'cream',
  'chili powder',
  'celery',
  'grated parmesan cheese',
  'ground cumin',
  'parmesan cheese',
  'chicken broth',
  'lime',
  'bacon',
  'egg yolks',
  'cheese',
  'bananas',
  'fresh lemon juice',
  'ginger',
  'zucchini',
  'mushrooms',
  'apples',
  'cayenne pepper',
  'strawberries',
  'dijon mustard',
  'fresh parsley',
  'avocado',
  'avocados',
  'worcestershire sauce',
  'worchestershire',
  'worcestershire',
  'red bell pepper',
  'nutmeg',
  'jalapeno chilies',
  'jalapeno chile',
  'jalapeno pepper',
  'jalapeno',
  'canola oil',
  'thyme',
  'tomato paste',
  'buttermilk',
  'egg whites',
  'balsamic vinegar',
  'ground beef',
  'scallions',
  'dried oregano',
  'cumin',
  'lime juice',
  'chicken stock',
  'light brown sugar',
  'maple syrup',
  'orange',
  'coconut oil',
  'white sugar',
  'yellow onion',
  'basil',
  'chicken breasts',
  'ground ginger',
  'cucumber',
  'confectioners sugar',
  'raisins',
  'diced tomatoes',
  'bread crumbs',
  'caster sugar',
  'castor sugar',
  'orange juice',
  'whole milk',
  'oregano',
  'freshly ground pepper',
  'cheddar cheese',
  'cheddar',
  'chives',
  'white wine',
  'boneless skinless chicken breasts',
  'bay leaf',
  'leeks',
  'chicken',
  'vinegar',
  'cherry tomatoes',
  'flat leaf parsley',
  'Italian parsley',
  'sesame oil',
  'whipping cream',
  'pure vanilla extract',
  'bay leaves',
  'fresh ginger',
  'onion powder',
  'walnuts',
  'red wine vinegar',
  'fresh basil',
  'margarine',
  'cilantro',
  'tomato sauce',
  'whipped cream',
  'mozzarella cheese',
  'coconut milk',
  'spring onions',
  'clove',
  'spice clove',
  'ground nutmeg',
  'plain flour',
  'mustard',
  'cocoa powder',
  'dry white wine',
  'almonds',
  'vegetable broth',
  'shredded cheddar cheese',
  'red pepper',
  'sweet potatoes',
  'bell pepper',
  'ketchup',
  'red pepper flakes',
  'chopped onion',
  'cilantro leaves',
  'ground pepper',
  'dried thyme',
  'semi-sweet chocolate morsels',
  'semi-sweet chocolate chips',
  'fresh lime juice',
  'rice vinegar',
  'rice wine vinegar',
  'green pepper',
  'curry powder',
  'unsweetened cocoa powder',
  'yoghurt',
  'yogurt',
  'freshly ground black pepper',
  'coriander',
  'whole wheat flour',
  'warm water',
  'chocolate chips',
  'rosemary',
  'shrimp',
  'chocolate',
  'black beans',
  'apple cider vinegar',
  'cooking spray',
  'melted butter',
  'lemon zest',
  'coarse salt',
  'sesame seeds',
  'pecans',
  'sauce',
  'rice',
  'green bell pepper',
  'peanut butter',
  'cold water',
  'green beans',
  'spinach',
  'celery ribs',
  'bread',
  'chopped pecans',
  'chopped walnuts',
  'cracked black pepper',
  'ground cloves',
  'capers',
  'white pepper',
  'fresh thyme',
  'ham',
  'dark brown sugar',
  'fresh rosemary',
  'white wine vinegar',
  'broccoli',
  'fresh cilantro',
  'dark chocolate',
  'hot sauce',
  'chopped parsley',
  'salsa',
  'mango',
  'sliced almonds',
  'almond flakes',
  'dried basil',
  'eggplant',
  'brinjal',
  'aubergine',
  'feta cheese',
  'feta',
  'chickpeas',
  'chick peas',
  'vanilla sugar',
  'crushed red pepper flakes',
  'green chilies',
  'turmeric',
  'pinenuts',
  'pine nuts',
  'corn',
  'chopped fresh cilantro',
  'boiling water',
  'almond extract',
  'rolled oats',
  'rolled oatmeal',
  'red wine',
  'white vinegar',
  'fat',
  'active dry yeast',
  'shortening',
  'cauliflower',
  'asparagus',
  'fresh mint',
  'fresh mint leaves',
  'raspberries',
  'white onion',
  'peaches',
  'pineapple',
  'cinnamon sticks',
  'cinnamon bark',
  'pasta',
  'blueberries',
  'half & half',
  'half and half',
  'dill',
  'cider vinegar',
  'red chili peppers',
  'cayenne',
  'sweetened condensed milk',
  'heavy whipping cream',
  'large egg yolks',
  'vegetable stock',
  'ground coriander',
  'fish sauce',
  'basil leaves',
  'cocoa',
  'italian seasoning',
  'vanilla beans',
  'chopped cilantro',
  'olives',
  'stem olives',
  'greek yogurt',
  'smoked paprika',
  'yeast',
  'cumin seed',
  'fresh basil leaves',
  'spices',
  'ice',
  'frozen peas',
  'pumpkin purée',
  'shredded mozzarella cheese',
  'lettuce',
  'grated lemon zest',
  'plum tomatoes',
  'creamy peanut butter',
  'smooth peanut butter',
  'large egg whites',
  'garlic salt',
  'dried cranberries',
  'baby spinach',
  'evaporated milk',
  'sweet onion',
  'hot water',
  'molasses',
  'spaghetti',
  'cabbage',
  'beef broth',
  'gelatin',
  'lean ground beef',
  'semisweet chocolate',
  'pears',
  'flour tortillas',
  'crème fraîche',
  'peas',
  'tomato purée',
  'salmon fillets',
  'rum',
  'fresh dill',
  'herbs',
  'pumpkin',
  'peanut oil',
  'peanuts',
  'juice',
  'mint leaves',
  'dry mustard',
  'goat cheese',
  'allspice',
  'new spice',
  'large garlic cloves',
  'kale',
  'butternut squash',
  'plain yogurt',
  'Tabasco Pepper Sauce',
  'Tabasco',
  'grated nutmeg',
  'sunflower oil',
  'cornmeal',
  'fine sea salt',
  'cashew nuts',
  'cashews',
  'ice cubes',
  'coconut',
  'ricotta cheese',
  'wine',
  'black peppercorns',
  'vodka',
  'cream of tartar',
  'chili pepper',
  'romaine lettuce',
  'romaine',
  'hazelnuts',
  'beets',
  'orange zest',
  'beer',
  'corn tortillas',
  'noodles',
  'light corn syrup',
  'bread flour',
  'cake flour',
  'cooked chicken',
  'chopped celery',
  'arugula',
  'rocket',
  'radishes',
  'almond milk',
  'vanilla ice cream',
  'boneless skinless chicken breast halves',
  'mascarpone',
  'cherries',
  'granny smith apples',
  'Granny Smith apples',
  'low sodium chicken broth',
  'pumpkin pie spice',
  'russet potatoes',
  'ground allspice',
  'pure maple syrup',
  'marjoram',
  'seasoning salt',
  'quinoa',
  'crushed tomatoes',
  'double cream',
  'panko breadcrumbs',
  'garam masala',
  'crushed red pepper',
  'self rising flour',
  'beef',
  'sausages',
  'sliced mushrooms',
  'oats',
  'broccoli florets',
  'red potato',
  'red-skinned potato',
  'bittersweet chocolate',
  'peppercorns',
  'agave nectar',
  'beef stock',
  'coriander seeds',
  'fresh mushrooms',
  'fennel seeds',
  'white bread',
  'puff pastry',
  'fruit', 
  'brandy',
  'cooking oil',
  'white chocolate',
  'cool whip',
  'Cool Whip Whipped Topping',
  'fresh blueberries',
  'dates',
  'kidney',
  'pineapple juice',
  'chia seeds',
  'Sriracha',
  'skim milk',
  'unbleached all-purpose flour',
  'applesauce',
  'vegetables',
  'fresh thyme leaves',
  'apple juice',
  'chopped tomatoes',
  'mint',
  'feta cheese crumbles',
  'slivered almonds',
  'shredded coconut',
  'chopped garlic',
  'coconut sugar',
  'softened butter',
  'dough',
  'barbecue sauce',
  'sun-dried tomatoes',
  'grape tomatoes',
  'coffee',
  'fresh oregano',
  'corn flour',
  'cornflour',
  'finely chopped onion',
  'salted butter',
  'parmigiano reggiano cheese',
  'parmigiano-reggiano',
  'roma tomatoes',
  'kidney beans',
  'sharp cheddar cheese',
  'fresh spinach',
  'coconut flour',
  'muscat',
  'black olives',
  'cooked rice',
  'mini marshmallows',
  'ground cardamom',
  'cardamom powder',
  'chili flakes',
  'bourbon whiskey',
  'bourbon',
  'dried parsley',
  'mustard seeds',
  'chiles',
  'chilies',
  'sage',
  'low sodium soy sauce',
  'almond flour',
  'lime wedges',
  'diced onions',
  'pasta sauce',
  'blackberries',
  'rolls',
  'cranberries',
  'baguette',
  'sunflower seeds',
  'tahini',
  'tuna',
  'long-grain rice',
  'graham cracker crumbs',
  'poppy seeds',
  'brown rice',
  'ground turkey',
  'chili sauce',
  'monterey jack',
  'monterey jack cheese',
  'chopped fresh thyme',
  'broth',
  'ground paprika',
  'pork tenderloin',
  'white chocolate chips',
  'brussels sprouts',
  'salmon',
  'salad',
  'dry bread crumbs',
  'starch',
  'starch powder',
  'seasoning',
  'prosciutto',
  'ground pork',
  'corn kernels',
  'hard-boiled egg',
  'swiss cheese',
  'chicken thighs',
  'roasted red peppers',
  'crushed pineapple',
  'pistachios',
  'clarified butter',
  'gruyere cheese' ]
[ 'tortilla chips',
  'cream of mushroom soup',
  'fresh orange juice',
  'yellow bell pepper',
  'sage leaves',
  'red cabbage',
  'purple cabbage',
  'apple cider',
  'pork',
  'fresh chives',
  'artichoke hearts',
  'lemon wedges',
  'rhubarb',
  'ghee',
  'plain greek yogurt',
  'self raising flour',
  'hot pepper sauce',
  'lime zest',
  'cacao powder',
  'yukon gold potatoes',
  'sweet paprika',
  'fine sweet paprika',
  'beansprouts',
  'bean sprouts',
  'baby carrots',
  'mint candies',
  'mints',
  'mint candy',
  'coconut flakes',
  'cream of chicken soup',
  'plums',
  'ranch dressing',
  'fresh coriander',
  'dry red wine',
  'candy',
  'dried rosemary',
  'golden raisins',
  'saffron',
  'sprinkles',
  'beans',
  'dried apricot',
  'parsnips',
  'chopped fresh chives',
  'minced onion',
  'marinara sauce',
  'marinara',
  'cannellini beans',
  'cannellini',
  'minced meat',
  'grated orange',
  'ice water',
  'couscous',
  'cottage cheese',
  'hoisin sauce',
  'hoisin',
  'pie crust',
  'fennel bulb',
  'french bread',
  'fresh raspberries',
  'old-fashioned oats',
  'apricots',
  'berries',
  'tortillas',
  'large shrimp',
  'taco seasoning',
  'button mushrooms',
  'star anise',
  'star anise seeds',
  'tarragon',
  'fresh parsley leaves',
  'food colouring',
  'food coloring',
  'sweetened coconut flakes',
  'curry',
  'shredded carrots',
  'pumpkin seeds',
  'instant yeast',
  'ground red pepper',
  'lentils',
  'boneless skinless chicken thighs',
  'lemongrass',
  'ground white pepper',
  'shredded cheese',
  'wheat flour',
  'unsweetened chocolate',
  'lettuce leaves',
  'frozen corn',
  'chopped nuts',
  'dry sherry',
  'fennel',
  'low-fat milk',
  'milk low-fat',
  'cocktail cherries',
  'maraschino cherries',
  'cardamom',
  'toasted sesame oil',
  'pancetta',
  'dark chocolate chips',
  'cake',
  'sliced green onions',
  'vegetable shortening',
  'kalamata',
  'kalamata olives',
  'baking potatoes',
  'basmati rice',
  'yellow cornmeal',
  'lemon peel',
  'dressing',
  'celery seed',
  'shiitake',
  'shitake mushroom',
  'shiitake mushrooms',
  'oyster sauce',
  'cookies',
  'dry yeast',
  'light soy sauce',
  'iceberg lettuce',
  'OREO® Cookies',
  'blue cheese',
  'graham crackers',
  'nonstick spray',
  'nonstick cooking spray',
  'grapes',
  'pesto',
  'horseradish',
  'ricotta',
  'gingerroot',
  'dark rum',
  'shredded sharp cheddar cheese',
  'elbow macaroni',
  'almond butter',
  'meat',
  'pimentos',
  'turkey',
  'frozen chopped spinach',
  'provolone cheese',
  'provolone',
  'watercress',
  'pinto beans',
  'unsweetened applesauce',
  'fish fillets',
  'sauerkraut',
  'ice cream',
  'smoked salmon',
  'syrup',
  'boneless chicken breast',
  'snow peas',
  'snowpeas',
  'steak',
  'table salt',
  'mirin',
  'cane sugar',
  'jam',
  'sambal chile paste',
  'sambal',
  'pizza doughs',
  'bicarbonate of soda',
  'pineapple chunks',
  'whole grain mustard',
  'milk chocolate',
  'mashed potatoes',
  'flaked coconut',
  'corn syrup',
  'ground almonds',
  'sherry',
  'vanilla instant pudding',
  'instant vanilla pudding',
  'mini chocolate chips',
  'firmly packed brown sugar',
  'sherry vinegar',
  'simple syrup',
  'milk chocolate chips',
  'macaroni',
  'yellow cake mix',
  'fresh tarragon',
  'tequila',
  'pickles',
  'pork chops',
  'hamburger buns',
  'seeds',
  'minced beef',
  'chicken wings',
  'chopped fresh mint',
  'shredded parmesan cheese',
  'vanilla essence',
  'english cucumber',
  'mustard powder',
  'nutritional yeast',
  'new potatoes',
  'mussels',
  'greens',
  'red food coloring',
  'mixed spice',
  'marshmallows',
  'yellow mustard',
  'celery root',
  'celery bulbs',
  'celeriac', 
  'egg noodles',
  'cognac',
  'whipped topping',
  'mandarin oranges',
  'peeled fresh ginger',
  'caraway seeds',
  'ginger root',
  'caramels',
  'tomato juice',
  'pudding mix',
  'coconut cream',
  'soy milk',
  'soya milk',
  'soymilk',
  'green cabbage',
  'medium shrimp',
  'toasted sesame seeds',
  'fresh cranberries',
  'cajun seasoning',
  '2% reduced-fat milk',
  'oatmeal',
  'ground flaxseed',
  'smetana',
  'arborio rice',
  'leaves',
  'crackers',
  'portabello mushroom',
  'portabella mushrooms',
  'portobello',
  'portobello mushrooms',
  'sugar pea',
  'sugar snap pea',
  'snap pea',
  'unflavored gelatin',
  'instant coffee',
  'unsweetened shredded dried coconut',
  'fresh breadcrumbs',
  'stevia',
  'chips',
  'almond meal',
  'prawns',
  'tofu',
  'linguine',
  'yellow squash',
  'cremini mushrooms',
  'turnips',
  'water chestnuts',
  'shredded Monterey Jack cheese',
  'sugar substitute',
  'gluten',
  'frosting',
  'grated lemon peel',
  'Nutella',
  'green olives',
  'quick-cooking oats',
  'penne pasta',
  'watermelon',
  'mixed salad greens',
  'white rice',
  'figs',
  'thyme leaves',
  'vegetable oil cooking spray',
  'nonstick vegetable spray',
  'tomato ketchup',
  'solid pack pumpkin',
  'canned pumpkin',
  'sweetener',
  'wine vinegar',
  'raw honey',
  'baby spinach leaves',
  'spanish onion',
  'grapeseed oil',
  'anchovy fillets',
  'parsley flakes',
  'whole wheat pastry flour',
  'lasagna noodles',
  'tamari soy sauce',
  'tamari',
  'grating cheese',
  'xanthan gum',
  'biscuits',
  'chillies',
  'toast',
  'sweet corn',
  'sweetcorn',
  'prepared horseradish',
  'vanilla bean paste',
  'garbanzo beans',
  'currant',
  'liqueur',
  'macadamia nuts',
  'celery salt',
  'salt and ground black pepper',
  'unsweetened almond milk',
  'crumbled blue cheese',
  'garlic paste',
  'Italian parsley leaves',
  'stewed tomatoes',
  'reduced sodium chicken broth',
  'parsley leaves',
  'pizza sauce',
  'soup',
  'poultry seasoning',
  'fresh tomatoes',
  'chervil',
  'low-fat quark',
  'bouillon',
  'italian sausage',
  'frozen blueberries',
  'minced ginger',
  'yellow peppers',
  'diced celery',
  'white beans',
  'caramel sauce',
  'chipotles in adobo',
  'peppermint extract',
  'semolina',
  'bbq sauce',
  'polenta',
  'gin',
  'stock',
  'orange liqueur',
  'chocolate syrup',
  'kiwi',
  'liquid smoke',
  '1% low-fat milk',
  'apricot jam',
  'dry coconut',
  'condensed milk',
  'light mayonnaise',
  'red kidney beans',
  'superfine sugar',
  'onion soup mix',
  'chicken stock cubes',
  'chicken bouillon cubes',
  'rice flour',
  'glaze',
  'bbq glaze',
  'coarse sea salt',
  'juniper berries',
  'lemon slices',
  'white flour',
  'long grain white rice',
  'gouda',
  'seasoned bread crumbs',
  'fish',
  'lard',
  'reduced sodium soy sauce',
  'flax seeds',
  'icing',
  'club soda',
  'beaten eggs',
  'medjool date',
  'red chili powder',
  'pomegranate seeds',
  'bacon slices',
  'cooked bacon',
  'pecorino romano cheese',
  'pecorino romano',
  'orange marmalade',
  'refried beans',
  'fresh pineapple',
  'orange peel',
  'pepperoni',
  'golden syrup',
  'firm tofu',
  'crabmeat',
  'grapefruit',
  'lemon extract',
  'dried cherry',
  'italian salad dressing',
  'italian dressing',
  'pitted dates',
  'green peas',
  'brie cheese',
  'hot pepper',
  'turkey breast',
  'corn oil',
  'tomatillos',
  'teas',
  'flax seed meal',
  'flaxseed meal',
  'fresh sage',
  'champagne',
  'penne',
  'artichokes',
  'vidalia onion',
  'chipotle chile',
  'ground lamb',
  'pie shell',
  'beef stock cubes',
  'beef bouillon cubes',
  'chinese five-spice powder',
  'five-spice',
  'brewed coffee',
  'cooked chicken breasts',
  'golden caster sugar',
  'raw cashews',
 
