'cage free eggs',
  'meat stock',
  'boiling potatoes',
  'wide noodles',
  'dried chile',
  'ground sirloin',
  'chicken meat',
  'clear honey',
  'canned black beans',
  'large marshmallows',
  'green lentil',
  'skirt steak',
  'baby bok choy',
  'whole grain bread',
  'chestnut mushrooms',
  'lean ground turkey',
  'roasted hazelnuts',
  'sweetened whipped cream',
  'safflower oil',
  'key lime juice',
  'cupcakes',
  'buffalo sauce',
  'flatbread',
  'flat bread',
  'summer squash',
  'dijon-style mustard',
  'endive',
  'cacao',
  'frozen hash brown potatoes',
  'vanilla powder',
  'mixed berries',
  'rib',
  'large potatoes',
  'barley',
  'fat free cream cheese',
  'sprouts',
  'french baguette',
  'peppermint',
  'breakfast sausages',
  'cherry juice',
  'golden delicious apples',
  'beef tenderloin',
  'Bisquick Baking Mix',
  'whole berry cranberry sauce',
  'low sodium chicken stock',
  'oat bran',
  'stout',
  'crushed pineapples in juice',
  'Baileys Irish Cream Liqueur',
  'gnocchi',
  'sandwiches',
  'sweet italian sausage',
  'manchego cheese',
  'manchego',
  'pepper flakes',
  'toasted slivered almonds',
  'halibut fillets',
  'deli ham',
  'red apples',
  'melon',
  'bouillon cube',
  'sparkling wine',
  'ear of corn',
  'kielbasa',
  'jello',
  'cake glaze',
  'arrowroot powder',
  'plantains',
  'peach slices',
  'dry roasted peanuts',
  'baked beans',
  'szechwan peppercorns',
  'sichuan peppercorns',
  'toasted coconut',
  'collard greens',
  'crispy rice cereal',
  'calvados',
  'pasta shells',
  'anise seed',
  'pork schnitzel',
  'sweet cherries',
  'Emmenthal',
  'Emmental',
  'emmentaler',
  'Emmenthaler',
  'rotel tomatoes',
  'allspice berries',
  'baking mix',
  'colby jack cheese',
  'flaked oats',
  'baby potatoes',
  'base',
  'Meyer lemons',
  'shaved parmesan cheese',
  'fenugreek seeds',
  'crumbled goat cheese',
  'orange flower water',
  'Cafe Boheme Liqueur',
  'Barritts Ginger Beer',
  'absolut mandrin'
  
  
